import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local';

const editorialBold = localFont({
  src: '../../public/font/Editorial/PPEditorialNew-Ultralight.otf',
  variable: '--font-editorial-light',
  display: 'swap',
});

const editorial = localFont({
  src: '../../public/font/Editorial/PPEditorialNew-Ultrabold.otf',
  variable: '--font-editorial-bold',
  display: 'swap',
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${editorialBold.variable} ${editorial.variable}`}>
        {children}
      </body>
    </html>
  );
}
